{% set name = "pyppdf" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/macchrome/winchrome/archive/v79.0.3945.79-r706915-Win64.tar.gz
    folder: dummy
    sha256: d121d83160dfe52b506e9946eac8ebe8691f148f6f3e26cf456b3451a91ab032
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    folder: .
    sha256: a065b44b8a3a63d659b028aa8b2bbb41e54504006d8e32194a4ecdfae29ac763

build:
  noarch: python
  number: 1
  entry_points:
    - pyppdf = pyppdf.pyppeteer_pdf:cli
    - pyppdf-replace-mathjax = pyppdf.replace_mathjax:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - certifi
    - click
    - litereval >=0.0.9
    - pyppeteer >=0.0.25

test:
  imports:
    - pyppdf
    - pyppdf.patch_pyppeteer
  commands:
    - pyppdf --help
    - pyppdf-replace-mathjax --help

about:
  home: https://github.com/kiwi0fruit/pyppdf
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Pyppeteer PDF. Print html sites and files to pdf via pyppeteer (uses patched pyppeteer that by default downloads updated Chromium revision via https with certifi)."
  doc_url: https://github.com/kiwi0fruit/pyppdf
  dev_url: https://github.com/kiwi0fruit/pyppdf

extra:
  recipe-maintainers:
    - kiwi0fruit
