travis:
  secure:
    BINSTAR_TOKEN: g6Rf00cqxIHF7ICudHvaxhhsP+MY17bNgTb1tws2hfnbqrm+DfQMOdGbDjeeboLhowl76cFXK+FnDGVvLtSv3ekGOFfvzBUeTyxefZOud7eEySOiH8StWDPOO1zmzA4w+cTHUUdl86VNcVRfqeVzfcp21l0hsXrumA7FT5KwZaOoDFK4Dz0XCFHA+tX9EBBZPl6hzZMKeVztsApEZqH8++LUCyNUoZl90IIKMaNdpHQiNORtX9cIaE87jEWyQyIj9wfSTnTsapyV79wiWH+b8DykxLeVjm53UvstFwiQGnByW4vvjQ9WEfZCV8ZaEwPTvwz63EK+DwN8hhlQNdytmJ1GARLYlm53kR1n4P9GttRU/FR1iqCmOGJ5CcGzvDrQuLaCBR2gfMZDfzccF4L2+Vkzrzal2WNWlRKxOUQrNnsSPpvnvFaZn4LOpWkrRk3pFSJ3h8pmrf0k07AlCHFuAF1GLtW9zTAeKCzdNRJOJgYDXJESii719CRrFPGSV2e84lnWxs5cK9B8IsDnoqeuezu3a5WjNDDiHJFZfEGC2kTlOEjzesAGruH7zDKAtCt5dkWjC88vJICgFUHCy8i9mU4rzUwTk3c3VUYikfauUS/7HpfKz63uRW2VERfnONuaO3Ugg3+12bxxy4caXeibvmpYPdU2B3LGq1ygL25p5YI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
win:
  enabled: False
