travis:
  secure:
    BINSTAR_TOKEN: OR+joWZmIpTd1SCuRfN1c4OGgTtTCfcq8Vd7VeN7ahWr/HgNQhPoBSIplx1TOIr7R0Fn+84cEAAFqTCNU7eDV8JHvLbYbEr0DAemfvFFppb7hbh7T2D3UIPYDD4oLAcaQf7ez136M1OIIa8tL5KwQE8ZkH33gI02mZRzPG2tEZdn474SgA2VEyRKxMUL6djxlBy9dZ7Sg+JF8c5DdsOIhWaSDSqlSa8e5nETFwT16WyWVNv5QktlSD0t0UeuzEgcg/0JHakPwqtfT1Sgn+VLKLALKpe+RB0TqHYLsHJ/gQofeKsFdK0ZpHvaDPE3y76QUx59u3kLOZi7A+cwm0QRrawr4wuJq0XJpksosA++wKhDD6A8BeS3FuaZzpilLwY8ZJlhDTPl7p9/mt/nGL8wORnKSnC7/WrN8A8QXa8uafMisPzcFkOlNRMohTzjc7O5i8PjhZw/51YcfAQbfVNJuJM9acSpXzhplb5JoCrEH5aSTBm3W7utNu0yCQDGURGfAGBherIMGSpnplnBxd1JQqcdmTmjKKNk2BSOhAwrIhQ4kJxqXeWa2Ssi8vwohUxm7bPAqKinOqAi9F+tZqthvzfGrFmlrbaPSbG48k6Em1fcyIxvwjXUuMaVP8bGifQJApY5DEhuueRTmZTi2f8Ghej5gZw1aNCVn70YUIvDYxc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
